Fail more graciously when using [[, $, as.list(), lapply(), or unlist() on a GAlignments object
This will now fail with:

  Error in getListElement(x, i, ...) :
    GAlignments objects don't support [[, $, as.list(), lapply(), or
    unlist()

instead of:

  Error: C stack usage  7969700 is too close to the limit